name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/modelcontextprotocol/servers.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          if git rev-parse --verify upstream/main; then
            git merge upstream/main --allow-unrelated-histories -m "Sync upstream"
            git push origin main
          else
            echo "Upstream branch 'main' does not exist. Skipping merge."
          fi
